services:
  - type: web
    name: samvidha-attendance-calculator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    preDeploy:
      - apt-get update && apt-get install -y \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxi6 \
          libxtst6 \
          libpangocairo-1.0-0 \
          libpango-1.0-0 \
          libcairo2 \
          libdrm2 \
          libgbm1 \
          libasound2 \
          libatspi2.0-0 \
          libwayland-client0 \
          libwayland-egl1 \
          libwayland-server0 \
          libxkbcommon0 \
          fonts-liberation
    envVars:
      - key: PORT
        value: 10000
