services:
  - type: web
    name: samvidha-attendance-calculator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    preDeploy:
      - apt-get update
      - apt-get install -y software-properties-common
      - add-apt-repository universe
      - apt-get update
      - apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - apt-get install -y chromium-browser || apt-get install -y chromium || echo "Failed to install chromium-browser or chromium"
      - which chromium-browser || which chromium || echo "Neither chromium-browser nor chromium found"
      - ls -l /usr/bin/chromium-browser || ls -l /usr/bin/chromium || echo "Chromium binary not found in /usr/bin"
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
