services:
  - type: web
    name: attendance-calculator
    runtime: node
    buildCommand: npm install && cd backend && npx puppeteer browsers install chrome
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /opt/render/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome
    healthCheckPath: /
    autoDeploy: true 
