services:
  - type: web
    name: attendance-calculator
    runtime: node
    buildCommand: |
      npm install
      cd backend
      npm install
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install puppeteer
      npx puppeteer browsers install chrome --path /opt/render/.cache/puppeteer
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /opt/render/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome
    healthCheckPath: /
    autoDeploy: true 
