services:
  - type: web
    name: samvidha-attendance-calculator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
